### ISSUE TITLE
Option to edit PolyData in-place for core processing functions

### ISSUE THREAD

**Issue by supersubscript** [akaszynski/vtkInterface#12]
### Proposed solution
There are some PolyData functions that I think would benefit from having an option to edit the input object in place. I would suggest adding this functionality as a function argument in the style of e.g. 
```python
    def Decimate(self, target_reduction, ..., inplace=False):

        <...>

        if inplace:
            self.Overwrite(decimate.GetOutput())
        else:
            return PolyData(decimate.GetOutput())
``` 

Candidate functions for this feature include (but aren't limited to)
* PolyData.Decimate
* PolyData.Boolean[Cut,Add,Union]
* PolyData.Normals (see [PR](https://github.com/akaszynski/vtkInterface/pull/10))
* PolyData.RemovePoints
* PolyData.TriFilter
* ~~PolyData.Subdivide~~ (already has it!)

Similarly, for the functions that exclusively **do** in-place operations, it might be good to add the flexibility to be able to return the object (such as for PolyData.Clean etc.).

### Motivation
Not having inplace arguments breaks code style consistency. Example:
```python
mesh.ClipPlane([0, 0, 0], [0,0,1])
mesh.ExtractLargest()
mesh.FillHoles(100.0)
mesh.FlipNormals()
normals = mesh.Normals()
mesh.SetNormals(*normals)
mesh.Clean()
mesh = mesh.Decimate(0.9)
```

**Comment by akaszynski** [comment]
I agree that most of these functions need an in-place bool argument.  I'll go ahead and add this over this weekend.

**Comment by akaszynski** [comment]
Added in commit https://github.com/akaszynski/vtkInterface/commit/61ca0af7395858887faefe23ab0006b1816d0371
