### ISSUE TITLE
PolyData from vertices and faces not working - either crashes or shows nothing

### ISSUE THREAD

**Issue by flutefreak7** [akaszynski/vtkInterface#18]
- Windows 10
 - python 3.6.4 (anaconda)
 - VTK version 8.1.1 (pip)
 - vtkInterface 0.9.3 (pip)

When I attempt to use PolyData with vertices and faces I either get a segfault style crash or for some simple demos I get an empty VTK render window.

For example, the code on this page: https://vtkinterface.readthedocs.io/en/latest/polydata.html:

    import numpy as np
    import vtkInterface

    # mesh points
    vertices = np.array([[0, 0, 0],
                         [1, 0, 0],
                         [1, 1, 0],
                         [0, 1, 0]])

    # mesh faces
    faces = np.hstack([[4, 0, 1, 2, 3],  # square
                       [3, 0, 1, 4],     # triangle
                       [3, 1, 2, 4]])    # triangle

    surf = vtkInterface.PolyData(vertices, faces)

    # plot each face with a different color
    surf.Plot(scalars=np.arange(3))

Just gives me an empty render window.

The following example segfaults:

    import vtkInterface
    import numpy as np
    from vtkInterface import PolyData

    verts = np.array([[0, 0, 0],
                      [0, 0, 1],
                      [0, 1, 0],
                      [1, 0, 1]], dtype=np.float64)
    faces = np.array([[0, 1, 2],
                      [1, 2, 3]], dtype=np.int64)
    pd = PolyData(verts, faces)
    pd.Plot()

When I follow the debugger it's the PolyData.SetPolys() line that causes the crash.

Just to be clear... if I instead build the triangles one at time using pure vtk it works fine.

    import numpy as np
    import vtk

    verts = np.array([[0, 0, 0],
                      [0, 0, 1],
                      [0, 1, 0],
                      [1, 0, 1]], dtype=np.float64)
    faces = np.array([[0, 1, 2],
                      [1, 2, 3]], dtype=np.int64)

    points = vtk.vtkPoints()
    triangles = vtk.vtkCellArray()

    for i, tri in enumerate(faces):
        p1 = verts[tri[0]]
        p2 = verts[tri[1]]
        p3 = verts[tri[2]]
        points.InsertNextPoint(*p1)
        points.InsertNextPoint(*p2)
        points.InsertNextPoint(*p3)

        triangle = vtk.vtkTriangle()
        triangle.GetPointIds().SetId(0, 3 * i + 0)
        triangle.GetPointIds().SetId(1, 3 * i + 1)
        triangle.GetPointIds().SetId(2, 3 * i + 2)
        triangles.InsertNextCell(triangle)

    polydata = vtk.vtkPolyData()
    polydata.SetPoints(points)
    polydata.SetPolys(triangles)

    mapper = vtk.vtkDataSetMapper()
    mapper.SetInputData(polydata)
    actor = vtk.vtkActor()
    actor.SetMapper(mapper)

    renderer = vtk.vtkRenderer()
    renWin = vtk.vtkRenderWindow()
    renWin.AddRenderer(renderer)
    iren = vtk.vtkRenderWindowInteractor()
    iren.SetInteractorStyle(vtk.vtkInteractorStyleTrackballCamera())
    iren.SetRenderWindow(renWin)
    renderer.AddActor(actor)
    renWin.SetSize(640, 480)
    renWin.Render()

    renWin.Render()
    iren.Start()

Any ideas?

**Comment by flutefreak7** [comment]
Figured it out!

When I separated things out and used `SetNumpyPoints` and `SetNumpyFaces`, I got a useful error:

`Exception: First column should contain the number of points per face`

...which I wasn't doing with my faces array.  The following now works as expected:

    import vtkInterface
    import numpy as np
    from vtkInterface import PolyData


    verts = np.array([[0, 0, 0],
                      [0, 0, 1],
                      [0, 1, 0],
                      [1, 0, 1]], dtype=np.float64)
    faces = np.array([[3, 0, 1, 2],
                      [3, 1, 2, 3]], dtype=np.int64)

    polydata = PolyData(verts, faces)

    polydata.Plot()

As for the example code, which of course *does* do the faces correctly, the faces refer to a vertex #4 that doesn't exist... adding that 5th vertex allows the example to not crash:

    import numpy as np
    import vtkInterface

    # mesh points
    vertices = np.array([[0, 0, 0],
                         [1, 0, 0],
                         [1, 1, 0],
                         [0, 1, 0],
                         [0.5, 0.5, 1.0]])

    # mesh faces
    faces = np.hstack([[4, 0, 1, 2, 3],  # square
                       [3, 0, 1, 4],     # triangle
                       [3, 1, 2, 4]])    # triangle

    surf = vtkInterface.PolyData(vertices, faces)

    # plot each face with a different color
    surf.Plot(scalars=np.arange(3))

**Comment by akaszynski** [comment]
Thanks for pointing this out.

I probably should add some error checking code that gives the user a useful error rather than just crashing the interpreter.  Doing this check will probably be slow, so I might just implement it in Cython.  There's a bunch of other functions that I've been meaning to move over from some of my internal work into ``vtkInterface``, so maybe this is a good chance for me to do it.

Any other recommendations?

**Comment by akaszynski** [comment]
Finally cleaned up the code.  Thanks for pointing this out.
