### ISSUE TITLE
jupyter notebook with vtki

### ISSUE THREAD

**Issue by chenray844** [akaszynski/vtkInterface#19]
hi all:
This project is very interesting for visualization based on VTK. 
I want to use `vtkInterface` with `jupyter notebook` then i can view the result in notebook. 
Maybe, it can integrate with [pythreejs](https://github.com/jupyter-widgets/pythreejs). 
Current, the result show in another window as following:

<img width="1135" alt="screen shot 2018-08-15 at 15 25 14" src="https://user-images.githubusercontent.com/2977266/44136477-8202b7a8-a09f-11e8-8350-905dc5367a05.png">

@akaszynski do you have a plan for rendering on jupyter ?

**Comment by akaszynski** [comment]
That’s a great idea.  A quick fix would be to have vtk render the plot in
the background and then write it to a temporary file, and read it in using
matplotlib.  I’ll cook something up.

**Comment by akaszynski** [comment]
This will display the rendered plot in a ``jupyter notebook``.  It doesn't even use matplotlib, just displays directly to the notebook.  Requires 0.10.0 or greater

See [Plotting in a Jupyter Notebook](https://vtkinterface.readthedocs.io/en/latest/examples.html?highlight=notebook#plotting-in-a-jupyter-notebook)

```python
import vtkInterface as vtki
sphere = vtki.Sphere()

# short example
cpos, image = sphere.Plot(notebook=True)

# long example
plotter = vtki.PlotClass(notebook=True)
plotter.AddMesh(sphere)
plotter.Plot()
```
