### ISSUE TITLE
module 'vtkInterface' has no attribute 'LoadMesh'

### ISSUE THREAD

**Issue by bastula** [akaszynski/vtkInterface#2]
I can get `tests.ShowWave()` to work, but none of the other examples run because LoadMesh isn't working.

vtkInterface 0.4.0 from pip
MacOS 10.13
Homebrew Python 3.6.2
Homebrew VTK 8.1.0

**Comment by akaszynski** [comment]
Fixed.  Forgot to change the examples with the API change.  Download 0.4.2 from pip.

**Comment by bastula** [comment]
Wow that was fast! It works perfectly.

Thanks for the quick update!

**Comment by nicola1312199** [comment]
Same happened to me:
ubuntu 16.04
python3.5 
vtk 8.1.1
vtkInterface 0.11.0

Thanks

**Comment by akaszynski** [comment]
The ``ShowWave`` function has been moved to examples as of 0.11.2:
```python
from vtkInterface import examples
examples.ShowWave()
```
