### ISSUE TITLE
File ..vtkInterface/examples/sphere.vtk does not exist

### ISSUE THREAD

**Issue by bastula** [akaszynski/vtkInterface#3]
I see `sphere.ply` in version control but not `sphere.vtk`?

**Comment by akaszynski** [comment]
Looks like another bug.  Fixed and commited here and uploaded to pypi as 0.4.3

Thanks for checking my work!

**Comment by bastula** [comment]
Thank you for the quick fixes and this great library. I think I will be able to finally use VTK in a sane manner in my projects!
