### ISSUE TITLE
Probably bug in UpdateCoordinates (plottingg.py)

### ISSUE THREAD

**Issue by Lishen1** [akaszynski/vtkInterface#4]
`def UpdateCoordinates(self, points, mesh=None, render=True):`
`        """ updates points of object (point only for now)`
`        assumes last inputted mesh if mesh left empty`
`        """'`
        `if mesh is None:`
            `mesh = self.mesh`
        `self.mesh.SetNumpyPoints(points)`
        `if render:`
            `self.Render()`

`self.mesh.SetNumpyPoints(points)` probable should be `mesh.SetNumpyPoints(points)`

**Comment by akaszynski** [comment]
Changed the line and committed it.  I'll publish to PyPi for 0.7.0

Thanks for the bug report!
