### ISSUE TITLE
Change LookUpTable in vtkInterface

### ISSUE THREAD

**Issue by nicoguaro** [akaszynski/vtkInterface#6]
I was checking and the LookUpTable (colormap) is hardcoded in vtkInterface. Is there any chance that we can change it?

Colormaps serve different purposes in different datasets and it would be nice to change. Furthermore, the rainbow colormap is considered to be suboptimal, see for example:

Borland, David, and Russell M. Taylor II. ["Rainbow color map (still) considered harmful."](https://data3.mprog.nl/course/15%20Readings/40%20Reading%204/Borland_Rainbow_Color_Map.pdf) IEEE computer graphics and applications 27.2 (2007): 14-17.

**Comment by akaszynski** [comment]
The rainbow colormap is indeed not usually the best option.  I've manually gone in and changed it in the past, but it would be better have a more user-friendly interface so it's easy to change.

Would something like matploblib's colormaps be sufficient?
https://matplotlib.org/examples/color/colormaps_reference.html
https://matplotlib.org/users/colormaps.html

**Comment by nicoguaro** [comment]
I would say that it would be interesting if you could pass the lookup table. But, those are definitely good options to start with.

**Comment by akaszynski** [comment]
Added colormaps.  See matplotlib documentation for available colormaps:
https://matplotlib.org/examples/color/colormaps_reference.html

Code sample:
```python
import vtkInterface
from vtkInterface import examples

# Load Grid
grid = vtkInterface.UnstructuredGrid(examples.hexbeamfile)

# scalar demo
plobj = vtkInterface.PlotClass()
plobj.AddMesh(grid, scalars=grid.points[:, 2], colormap='bwr')
plobj.AddScalarBar()
plobj.Plot()
```
![screenshot from 2018-03-08 00-00-20](https://user-images.githubusercontent.com/11981631/37123251-c69fe92c-2263-11e8-8e18-eb80a23b056a.png)

**Comment by nicoguaro** [comment]
It works smoothly, thanks!
